### ISSUE TITLE
where is "rf" in receptive_field?

### ISSUE THREAD

**Issue by doublemanyu** [Shikhargupta/Spiking-Neural-Network#17]
hey man, I am running your code rescently. It's a wonderful work. However, I met a question and I need your help.
When i run the classify.py in classification file, i found the error "from receptive_field import rf" was wrong. I check up the receptive_field file, there is not a "rf" in there. So where is "rf" in receptive_field?
Looking forward to your reply.

**Comment by Shikhargupta** [comment]
It's right there in this file - https://github.com/Shikhargupta/Spiking-Neural-Network/blob/master/classification/recep_field.py
