### ISSUE TITLE
classification

### ISSUE THREAD

**Issue by assadRasheed** [Shikhargupta/Spiking-Neural-Network#2]
how can i use these spikes count in python that can classify images

**Comment by Shikhargupta** [comment]
Hey @assadRasheed. I guess you are talking about the spike_count variable in Spiking-Neural-Network/classification/classify.py.
This variable stores the number of spikes fired by each neuron in output layer. For a particular image the neuron with maximum number of spikes corresponds to the class that image belongs to. For eg. suppose neuron 1 is trained for 'X' and neuron 2 for 'O' and feed an unknown image (one out of these 2 pattern). If 1 fires most then we can say that input image belongs to class 'X' and vice versa.

**Comment by assadRasheed** [comment]
THANKS.
Please sir code further in Spiking-Neural-Network/classification/classify.py in such a way that it tells us which class the input image belong.
i tried a lot but failed to get the results.
