### ISSUE TITLE
ImportError   :cannot import name 'reconst'

### ISSUE THREAD

**Issue by assadRasheed** [Shikhargupta/Spiking-Neural-Network#3]
ImportError                               Traceback (most recent call last)
<ipython-input-7-d14e646d6ad6> in <module>()
      5 import cv2
      6 from spike_train import encode
----> 7 from reconstruct import reconst
      8 from weight_initialization import learned_weights_x
      9 from weight_initialization import learned_weights_o

ImportError: cannot import name 'reconst'

**Comment by Shikhargupta** [comment]
Thanks for bringing this to notice. I will remove this import as it is of no use in classification.
