### ISSUE TITLE
IndexError: index 16 is out of bounds for axis 0 with size 16

### ISSUE THREAD

**Issue by assadRasheed** [Shikhargupta/Spiking-Neural-Network#4]
IndexError                                Traceback (most recent call last)
<ipython-input-7-c03aa32a3c81> in <module>()
     52 
     53                 #Convolving image with receptive field
---> 54                 pot = rf(img)
     55 
     56                 #Generating spike train

**# C:\Users\pc\AnacondaProjects\Spiking-Neural-Network-master\training\recep_field.py** in rf(inp)
     35                                 for n in ran:
     36                                         if (i+m)>=0 and (i+m)<=par.pixel_x-1 and (j+n)>=0 and (j+n)<=par.pixel_x-1:
---> 37                                                 summ = summ + w[ox+m][oy+n]*inp[i+m][j+n]/255
     38                         pot[i][j] = summ
     39         return pot

IndexError: index 16 is out of bounds for axis 0 with size 16

this happens when i change the image from 1.png to 100.png or 101.png given below to
for k in range(par.epoch):
	for i in range(322,323):
		print (i,"  ",k)
		img = cv2.imread("images/100.png", 0)

**Comment by henokhope1** [comment]
@assadRasheed  did you find a way to fix the above issue?

**Comment by henokhope1** [comment]
If we use proper image the issue will not happen

**Comment by Amri95** [comment]
Please recommend the solution for this issue.
![github](https://user-images.githubusercontent.com/37174642/46578328-6e299b80-ca38-11e8-81bf-3ee72dd529da.PNG)

**Comment by iormaoro** [comment]
That can happen when img loaded is not the same type used by his examples. Do some prints when he does the loads and see the differences with yours ones (Grayscale,...). That happened to me.

**Comment by liuYing77** [comment]
Exactly,you can change your the size of image, we usualy load image that is 28*28

**Comment by Amri95** [comment]
> Exactly,you can change your the size of image, we usualy load image that is 28*28

Can you please tell me what are the parameters i need to change if i use the image of 128*128  ?
