### ISSUE TITLE
classify error

### ISSUE THREAD

**Issue by XSNXPY** [Shikhargupta/Spiking-Neural-Network#5]
I have a different classification results  for each training.(I made n = 10 to recognize digits)
here are two different training results
322    0
winner is 2
322    1
winner is 2
322    2
winner is 2
322    3
winner is 2
322    4
winner is 2
322    5
winner is 2
322    6
winner is 2
322    7
winner is 2
322    8
winner is 2
322    9
winner is 2

322    0                         
winner is 4
322    1
winner is 4
322    2
winner is 4
322    3
winner is 4
322    4
winner is 4
322    5
winner is 4
322    6
winner is 4
322    7
winner is 4
322    8
winner is 4
322    9
winner is 4

**Comment by Lunaphied** [comment]
Are you sure it was trained on all the data/is loading in all the weights? The base code in the repository doesn't support this easily.
