### ISSUE TITLE
Class neuron haven't got Pth attribute

### ISSUE THREAD

**Issue by TxusLopez** [Shikhargupta/Spiking-Neural-Network#8]
Hi,

My code launches an error due to the class _neuron_ haven't got _Pth_ attribute. Is the class incomplete?

Thanks in advance

**Comment by HopefulRational** [comment]
Hi, @TxusLopez 
I haven't gone through the whole code but in **neuron/neuron.py** the @Shikhargupta sets Pth to 25 so may be having 
`self.Pth = 25` in `__init__()` may help.
